//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class servieRating
    {
        public int id { get; set; }
        public Nullable<double> rating { get; set; }
        public string serviceType { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> rid { get; set; }
    }
}
